common:
  etcd:
    endpoints:
      - "192.168.0.102:2379"
    username: "admin"
    password: "admin     "

  apps:
    demo:
      name: "demo"
      host: 192.168.0.99
      port: 7000
      gateway:
        port: 8080
    example:
      name: "example"
      host: 192.168.0.99
      port: 7002
      gateway:
        port: 8082